name: todo_common
description: Sample TODO app with polymer2+DDC
version: 0.0.1
dependencies:
 logging: any
 polymer_element: any
 built_collection: "^1.4.0"

#   path: ../../polymer_element
dependency_overrides:
 polymer_element:
  path: ../../polymer_element
 polymerize_common:
  path: ../../polymerize_common
# polymer_elements:
#  path: /home/vittorio/Develop/dart/polymer_elements
 html5:
  path: ../../html_lib
 polymer_elements:
  git:
    url: https://github.com/polymer-dart/polymerize_elements.git
    ref: v0.3.4
# js:
#  path: /home/vittorio/.pub-cache/hosted/pub.dartlang.org/js-0.6.1
dev_dependencies:
#  polymerize: ^0.8.5
  polymerize:
    path: ../../polymerize

transformers:
 - polymerize